name: Release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "Register QEMU to /proc/sys/fs/binfmt_misc"
      run: docker run --privileged --rm tonistiigi/binfmt --install all
    - name: "Fetch buildx binary"
      run: |
        wget -O buildx https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
        chmod +x buildx
    - name: "Initialize buildx"
      run: |
        ./buildx create --name cross --platform=amd64,arm,arm64,s390x,ppc64le  --use
        ./buildx inspect --bootstrap
    - name: "Build binaries from Dockerfile.artifact"
      run: ./buildx build -o /tmp --platform=amd64,arm64,arm,s390x,ppc64le -f Dockerfile.artifact .
    - name: "Create /tmp/artifact"
      run: |
        mkdir -p /tmp/artifact
        mv /tmp/linux_amd64/slirp4netns /tmp/artifact/slirp4netns-x86_64
        mv /tmp/linux_arm64/slirp4netns /tmp/artifact/slirp4netns-aarch64
        mv /tmp/linux_arm_v7/slirp4netns /tmp/artifact/slirp4netns-armv7l
        mv /tmp/linux_s390x/slirp4netns /tmp/artifact/slirp4netns-s390x
        mv /tmp/linux_ppc64le/slirp4netns /tmp/artifact/slirp4netns-ppc64le
    - name: "SHA256SUMS"
      run: (cd /tmp/artifact; sha256sum *) | tee /tmp/SHA256SUMS
    - name: "The sha256sum of the SHA256SUMS file"
      run: sha256sum /tmp/SHA256SUMS
    - name: "Prepare the release note"
      run: |
        tag="${GITHUB_REF##*/}"
        shasha=$(sha256sum /tmp/SHA256SUMS | awk '{print $1}')
        libslirp_version=$(/tmp/artifact/slirp4netns-x86_64 -v | grep -oP '^libslirp: \K\S*')
        libseccomp_version=$(/tmp/artifact/slirp4netns-x86_64 -v | grep -oP '^libseccomp: \K\S*')
        ubuntu_version=$(grep -oP '^ARG UBUNTU_VERSION=\K\S*' Dockerfile.artifact)
        cat << EOF | tee /tmp/release-note.txt
        ${tag}

        #### Changes
        (To be documented)

        #### Install
        \`\`\`
        curl -o slirp4netns --fail -L https://github.com/${{ github.repository }}/releases/download/${tag}/slirp4netns-\$(uname -m)
        chmod +x slirp4netns
        \`\`\`

        #### About the binaries
        The binaries are statically linked with libslirp ${libslirp_version} and libseccomp ${libseccomp_version} using Ubuntu ${ubuntu_version}.

        The binaries were built automatically on GitHub Actions.
        The build log is available for 90 days: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        The sha256sum of the SHA256SUMS file itself is \`${shasha}\` .
        EOF
    - name: "Create release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF##*/}"
        asset_flags=()
        for f in /tmp/artifact/* /tmp/SHA256SUMS; do asset_flags+=("-a" "$f"); done
        hub release create "${asset_flags[@]}" -F /tmp/release-note.txt --draft "${tag}"
