name: Release
on:
  push:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-24.04
    # The maximum access is "read" for PRs from public forked repos
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: write  # for releases
      id-token: write  # for provenances
      attestations: write  # for provenances
    steps:
    - uses: actions/checkout@v4
      with:
        # Reproduce the exact commit hash value
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v3
    - name: Cache apt
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          var-cache-apt
          var-lib-apt
        key: var-cache-apt-${{ hashFiles('Dockerfile.artifact') }}
    - name: inject var-cache-apt into docker
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        cache-map: |
          {
            "var-cache-apt": "/var/cache/apt",
            "var-lib-apt": "/var/lib/apt"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
    - name: "Build binaries from Dockerfile.artifact"
      run: docker buildx build -o /tmp/slirpbuilds --build-arg SOURCE_DATE_EPOCH --platform=amd64,arm64,arm,s390x,ppc64le,riscv64 -f Dockerfile.artifact .
    - name: "Create /tmp/artifact"
      run: |
        mkdir -p /tmp/artifact
        mv /tmp/slirpbuilds/linux_amd64/slirp4netns /tmp/artifact/slirp4netns-x86_64
        mv /tmp/slirpbuilds/linux_arm64/slirp4netns /tmp/artifact/slirp4netns-aarch64
        mv /tmp/slirpbuilds/linux_arm_v7/slirp4netns /tmp/artifact/slirp4netns-armv7l
        mv /tmp/slirpbuilds/linux_s390x/slirp4netns /tmp/artifact/slirp4netns-s390x
        mv /tmp/slirpbuilds/linux_ppc64le/slirp4netns /tmp/artifact/slirp4netns-ppc64le
        mv /tmp/slirpbuilds/linux_riscv64/slirp4netns /tmp/artifact/slirp4netns-riscv64
        echo "${SOURCE_DATE_EPOCH}" >/tmp/artifact/SOURCE_DATE_EPOCH
    - name: "Build deb"
      run: |
        VERSION="100:$(/tmp/artifact/slirp4netns-x86_64 -v | head -1 | cut -d " " -f 3)-ipv6"
        PKG_PATH="/tmp/slirp4netns_${VERSION}_amd64"
        mkdir -p "${PKG_PATH}/usr/bin"
        mkdir -p "${PKG_PATH}/usr/share/man/man1"
        mkdir -p "${PKG_PATH}/DEBIAN"
        gzip ./slirp4netns.1
        mv ./slirp4netns.1.gz "${PKG_PATH}/usr/share/man/man1/"
        cp /tmp/artifact/slirp4netns-x86_64 "${PKG_PATH}/usr/bin/slirp4netns"
        chmod 0755 "${PKG_PATH}/usr/bin/slirp4netns"
        echo "Package: slirp4netns
        Maintainer: root <root@localhost.localdomain>
        Version: ${VERSION}
        Architecture: amd64
        Section: devel
        Priority: optional
        Homepage: https://github.com/rootless-containers/slirp4netns
        Description: User-mode networking for unprivileged network namespaces
         slirp4netns provides user-mode networking for unprivileged network
         namespaces.
         .
         slirp4netns allows connecting a network namespace to the Internet in a
         completely unprivileged way, by connecting a TAP device in a network
         namespace to the usermode TCP/IP stack (\"slirp\")." > "${PKG_PATH}/DEBIAN/control"
        dpkg-deb --build --root-owner-group "${PKG_PATH}"
        export DEB=$(basename $(echo "${PKG_PATH}")).deb
        mv "/tmp/${DEB}" "/tmp/artifact/${DEB//:/_}"
    - name: "SHA256SUMS"
      run: (cd /tmp/artifact; sha256sum *) | tee /tmp/SHA256SUMS
    - name: "The sha256sum of the SHA256SUMS file"
      run: sha256sum /tmp/SHA256SUMS
    - name: "Prepare the release note"
      run: |
        tag="${GITHUB_REF##*/}"
        shasha=$(sha256sum /tmp/SHA256SUMS | awk '{print $1}')
        libslirp_version=$(/tmp/artifact/slirp4netns-x86_64 -v | grep -oP '^libslirp: \K\S*')
        libseccomp_version=$(/tmp/artifact/slirp4netns-x86_64 -v | grep -oP '^libseccomp: \K\S*')
        ubuntu_version=$(grep -oP '^ARG UBUNTU_VERSION=\K\S*' Dockerfile.artifact)
        cat << EOF | tee /tmp/release-note.txt
        #### Changes
        (To be documented)

        #### Install
        \`\`\`
        curl -o slirp4netns --fail -L https://github.com/${{ github.repository }}/releases/download/${tag}/slirp4netns-\$(uname -m)
        chmod +x slirp4netns
        \`\`\`

        #### About the binaries
        The binaries are statically linked with libslirp ${libslirp_version} and libseccomp ${libseccomp_version} using Ubuntu ${ubuntu_version}.

        The binaries were built automatically on GitHub Actions.
        The build log is available for 90 days: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        The sha256sum of the SHA256SUMS file itself is \`${shasha}\` .

        The binaries should be reproducible with the following command:
        \`\`\`
        docker buildx build \
          -o /tmp/slirpbuilds \
          --build-arg SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} \
          --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=1 \
          --platform=amd64,arm64,arm,s390x,ppc64le,riscv64 \
          -f Dockerfile.artifact \
          "https://github.com/${{ github.repository }}.git#${tag}"
        \`\`\`
        EOF
    - uses: actions/attest-build-provenance@v2
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      with:
        subject-path: |
          /tmp/artifact/*
          /tmp/SHA256SUMS
    - name: "Create release"
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF##*/}"
        gh release create -F /tmp/release-note.txt --draft --title "${tag}" "${tag}" /tmp/artifact/* /tmp/SHA256SUMS
